# Configure.
env: TOX_ENV=py
language: python
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=lint
      after_success:
        - echo
    - python: 3.6
      env: TOX_ENV=docs
      
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
sudo: false

# Run.
install: pip install tox
script: tox -e $TOX_ENV
